name: Build, bump tag version and release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install llvm
        uses: ./.github/actions/install_llvm
      - name: Build project
        run: cargo build --release --locked
      - name: Bump version and push tag/create release point
        uses: mathieudutour/github-tag-action@v5.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: bump_version
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/rocklang
          asset_name: rocklang-${{ matrix.os }}-amd64
          tag: ${{ steps.bump_version.outputs.new_tag }}
          overwrite: true
