name: Build, bump tag version and release

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

  release_assets:
    name: Release assets
    needs: release
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install llvm
        if: ${{ runner.os != 'Windows' }}
        uses: ./.github/actions/install_llvm

      - name: Install llvm
        if: ${{ runner.os == 'Windows' }}
        run: Invoke-WebRequest -OutFile llvm.7z https://github.com/vovkos/llvm-package-windows/releases/download/llvm-master/llvm-13.0.0-windows-amd64-msvc15-libcmt.7z
        shell: pwsh

      - name: Extract llvm
        if: ${{ runner.os == 'Windows' }}
        run: 7z.exe e .\llvm.7z -oC:\LLVM13
        shell: pwsh

      - name: Build project when platform == windows
        env:
          LLVM_SYS_130_PREFIX: "C:\LLVM13"
        if: ${{ runner.os == 'Windows' }}
        run: cargo build --release --locked

      - name: Build project when platform != windows
        if: ${{ runner.os != 'Windows' }}
        run: cargo build --release --locked

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: rocklang-${{ matrix.config.os }}
          asset_path: target/release/rocklang
          asset_content_type: application/octet-stream
